import fs from 'fs';
import path from 'path';
import { CodeGraph } from '../types/graph';

const MARKER_START = '<!-- cgraph:start -->';
const MARKER_END = '<!-- cgraph:end -->';

function buildSection(graph: CodeGraph): string {
  const { stats, nodes, projectName } = graph;
  const topFiles = nodes
    .filter((n) => n.type === 'file')
    .slice(0, 20)
    .map((n) => `- ${n.name}`)
    .join('\n');

  const langList = Object.entries(stats.languages)
    .map(([lang, count]) => `${lang} (${count} files)`)
    .join(', ');

  const classes = nodes
    .filter((n) => n.type === 'class')
    .slice(0, 15)
    .map((n) => `- \`${n.name}\` in \`${n.filePath}\``)
    .join('\n');

  const functions = nodes
    .filter((n) => n.type === 'function')
    .slice(0, 20)
    .map((n) => `- \`${n.name}\` in \`${n.filePath}\` (line ${n.startLine})`)
    .join('\n');

  return `${MARKER_START}
## Code Intelligence (cgraph)

**Project:** ${projectName}
**Last analyzed:** ${graph.analyzedAt}
**Stats:** ${stats.totalFiles} files · ${stats.totalFunctions} functions · ${stats.totalClasses} classes
**Languages:** ${langList}

### Key Files
${topFiles || 'N/A'}

### Classes & Interfaces
${classes || 'N/A'}

### Top-level Functions
${functions || 'N/A'}

> This section is auto-generated by [cgraph](https://github.com/NSLog0/cgraph). Run \`cgraph analyze <path>\` to update.
${MARKER_END}`;
}

export function generateClaudeMd(projectPath: string, graph: CodeGraph): void {
  const claudeMdPath = path.join(graph.projectPath, 'CLAUDE.md');
  const section = buildSection(graph);

  if (!fs.existsSync(claudeMdPath)) {
    fs.writeFileSync(claudeMdPath, `# ${graph.projectName}\n\n${section}\n`, 'utf-8');
    return;
  }

  let content = fs.readFileSync(claudeMdPath, 'utf-8');
  const startIdx = content.indexOf(MARKER_START);
  const endIdx = content.indexOf(MARKER_END);

  if (startIdx !== -1 && endIdx !== -1) {
    content = content.slice(0, startIdx) + section + content.slice(endIdx + MARKER_END.length);
  } else {
    content = content.trimEnd() + '\n\n' + section + '\n';
  }

  fs.writeFileSync(claudeMdPath, content, 'utf-8');
}
